src/config/routes.rb
Rails.application.routes.draw do

  post 'modal/login' => 'login'
  get 'modal/signup' => 'modal'
  get 'modal/forgot' => 'forgot'


  devise_for :users
  root to: 'profiles#index'

  #Static Pages
  # scope shallow_prefix: "pages" do
    get 'pages/about' => 'pages#about', as: :about
    get 'pages/contact' => 'pages#contact', as: :contact
    get 'pages/testimonies' => 'pages#testimonies', as: :testimonies
  # end


  resources :profiles do
    resources :messages
    resources :payments, only: [:new, :create]
    get '/photos' => 'profiles#photos'#, as: :photos
    get '/hookup' => 'profiles#hookup'
    get '/matches' => 'profiles#matches'
    get '/interests' => 'profiles#interests'
    post '/interests' => 'profiles#update_interests'
  end
  get '/success' => 'payments#success'
  get '/cancel' => 'payments#cancel'
  post '/likes' => 'profiles#update_likes'

  get '/messages' => 'messages#index'

  get "search/index"
    # patch '/profiles/:id'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

src/app/models/profile.rb
class Profile < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  #validation
  validates :name, presence: true
  validates :user_id, uniqueness: true
  after_commit :add_default_profile_pic, on: [:create, :update]

  #has_many_and_belongs_to_many
  has_and_belongs_to_many :interests
  has_and_belongs_to_many :likes
  has_many :messages

  #belongs_to
  belongs_to :user

  #active storage
  has_one_attached :pic
  has_many_attached :photos



  def avatar
    self.pic.variant(resize: "150x150!").processed#.service_url #processed.service_url
  end

  def avatar_small
    self.pic.variant(resize: "50x50!").processed#.service_url #processed.service_url
  end

  private
  #adds a default profile picture to a profile if none is provided
  def add_default_profile_pic
    unless pic.attached?
      self.pic.attach(io: File.open(Rails.root.join("app", "assets", "images", "anon.png")), filename: 'anon.png', content_type: "image/png")
    end
  end
end

src/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  #authenticate_user only on the new and edit methods
  before_action :authenticate_user!, only:[:new, :edit]
  before_action :set_profile, only: [:show, :edit, :update, :update_interests, :update_likes]

  def index
    #find all profiles on the root path, if user has a profile theirs is excluded from the results
    @profiles = Profile.all
    if user_signed_in? && current_user.profile != nil
      @profiles = Profile.where.not(id: current_user.profile.id)
    else
      @profiles = Profile.all
    end
  end

  def new
    #create a new Profile
    @profile = Profile.new
    #give the user the option to set their likes on the New view
    # @interests = Interest.all
  end

  def create
    #create a new Profile, inferring the user_id based on their devise user_id
    data = profile_params
    data[:user_id] = current_user.id
    @profile = Profile.new(data)
    #if a profile pic is attached, it will be slugged into the user profile
    #other wise the default is selected.
    @profile.pic.attach(profile_params[:pic])

    #on profile creation, an instance of the Like class is created that matches them
    if @profile.save
      Like.create!(profile_id: @profile.id)
      redirect_to profile_path(@profile)
    else
      render :new
    end
  end

  def show
    #searches for all profiles that like the current user
    @result = Like.find_by_sql "SELECT profile_id FROM likes_profiles WHERE like_id = #{@profile.id}"
    @likes = {}
    @result.each do |like|
      @likes[like.profile_id] = Profile.find(like.profile_id)
    end
  end

  def edit
  end

  def update
    if @profile.update(profile_params)
      redirect_to profile_path(@profile)
    else
      render :edit
    end
  end

  def update_interests
    #empty array is created then for each of the selected inputs they are added
    #to the profile
    @profile.interests = []
    params[:interests].each do |i|
      @profile.interests.push(Interest.find(i))
    end
    @profile.save
    redirect_to profile_path(@profile)
  end

  def update_likes#(home = false)

    #when liking another profile, the 'liker' is added to the "likee's" list of 'likers'
    #when the 'likee' visits their own page they can see and like back.

    liker = current_user.profile
    liker.likes.push(Like.find(@profile.id))
    # if home == true
    #   render profile_path(current_user)
    # else
    #   flash[:notice] = "Wow, great choice!"
    #   render :show
    # end
    flash[:notice] = "Wow, great choice!"
    render :show
  end

  def photos
    #show all photos
    @profile = Profile.friendly.find(params[:profile_id])
  end

  def interests
    #show all available interests to the profile
    @profile = Profile.friendly.find(params[:profile_id])
    @interests = Interest.all
  end

  def matches
    #finding all the profiles that I like
    @my_likes = Profile.friendly.find(current_user.profile.id).likes
    #then finding all the profiles that like me
    @people_who_like_me = Like.find_by_sql "SELECT profile_id FROM likes_profiles WHERE like_id = #{current_user.profile.id}"
    #adding each profile to an available array to use in the views.
    #there was a better way to this but i am to afraid to change anything and break it.
    @profiles = []
    @people_who_like_me.each do |like|
      @profiles.push(Profile.find(like.profile_id))
    end
  end

  def hookup
  end

  private
  def set_profile
    @profile = Profile.friendly.find(params[:id])
  end

  def profile_params
    params.require(:profile).permit(:name, :bio, :pic, photos: [])
  end
end

src/app/helpers/profiles_helper.rb
module ProfilesHelper
end

src/app/views/profiles/_banner.html.erb
<div id='profile-banner' class='nav-wrapper blue'>
  <div class='profile-pic container'>
    <div class="row">
      <div class="col s12 m12">
        <% if @profile.pic.attached? %>
          <div style="width:150px; height:auto;">
            <%= image_tag @profile.avatar, :class => 'circle' %>
          </div>
        <% end %>
      </div>
      <div class="col s12 m12 like">
        <% if user_signed_in? && current_user.profile != nil && current_user.profile.user_id != @profile.id %>
          <% if !current_user.profile.likes.any? {|p| p.profile_id == @profile.id} %>
            <%= form_for @profile, url: {action: "update_likes", controller: "profiles", params: {:id => @profile.id}}, :method => :POST do |f| %>
              <%= f.submit "I Like This" %>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

src/app/views/profiles/_form.html.erb
<div class='row'>
  <%= simple_form_for @profile do |f| %>
    <div class='col s12 m6'
      <h6>Profile Pic</h6>
      <%= f.file_field :pic%>
      <%= f.input :name %>
      <%= f.input :bio %>
      <%= f.button :submit %>
    </div>
  <% end %>
</div>

src/app/views/profiles/edit.html.erb
<%= provide(:active, "container") %>

<h4>Edit</h4>
<%= render partial: 'form' %>
<%= link_to "Back", profile_path(@profile) %>

src/app/views/profiles/hookup.html.erb
<h4>Hookup</h4>
<h5>Bow Chica Wow Wow</h5>
<h6>future stuff</h6>

src/app/views/profiles/index.html.erb
<%= provide(:active, "container") %>
<%= render partial: 'partials/search' %>

<div class='row'>
  <% @profiles.each do |p| %>
    <%= render partial: 'partials/card', locals: {profile: p} %>
  <% end %>
</div>

src/app/views/profiles/interests.html.erb
<%= provide(:active, "container") %>
<%= provide(:banner, 'profiles/banner') %>

<h4>Interests</h4>
<p>
  I have <%= @profile.interests.count %> interests
</p>
<% @profile.interests.each do |interest| %>
  <%= interest.interest %>
<% end %>

<% if @profile.user_id == current_user.profile.id %>
  <h4>Add Interests</h4>
  <div>
    <%= form_for @profile, url: {action: "update_interests"}, :method => :POST do |f| %>
      <% @interests.each do |i| %>
        <% if @profile.interests.include?(Interest.find(i.id)) %>
          <p>
            <label>
              <input type="checkbox" checked="checked" value="<%= i.id %>" name="interests[]" />
              <span><%= i.interest %></span>
            </label>
          </p>
        <% else %>
          <p>
            <label>
              <input type="checkbox" value="<%= i.id %>" name="interests[]" />
              <span><%= i.interest %></span>
            </label>
          </p>
        <% end %>
      <% end %>
      <br>
      <%= f.submit %>
    <% end %>
  </div>
<% end %>
<%= link_to "Back", profile_path(@profile) %>

src/app/views/profiles/matches.html.erb
<h4>My Matches</h4>
<% if @profiles.empty? || @profiles.length == 0 %>
  <p>Brrrr its chilly in here.</p>
<% else %>
  <% @my_likes.each do |like| %>
    <% @profiles.each do |profile| %>
      <% if like.id == profile.id %>
        <p>You've matched with <%= profile.name %> | <%= link_to 'Make a Date', new_profile_payment_path %></p>
      <% end %>
    <% end %>
  <% end %>
<% end %>

src/app/views/profiles/new.html.erb
<%= provide(:active, "container") %>
<h4>New</h4>

<%= render partial: 'form' %>

src/app/views/profiles/photos.html.erb
<%= provide(:active, "container") %>
<%= provide(:banner, 'profiles/banner') %>
  <h4><%= @profile.name %>'s Photos</h4>
  <% if user_signed_in? && current_user.profile != nil %>
    <% if @profile.id == current_user.profile.id %>
      <%= simple_form_for @profile do |f| %>
        <%= f.file_field :photos, multiple: true %>
        <br>
        <%= f.submit 'Save', class: "waves-effect waves-light btn"  %>
      <% end %>
    <% end %>
  <% end %>
  <%= link_to "Back", profile_path(@profile) %>
  <div class='row'>
    <% @profile.photos.each do |photo| %>
      <div class="col s12 m6 l4 center responsive-img-container" style="height:300px;">
        <%= image_tag photo, :class => 'responsive-img materialboxed' %>
      </div>
  <% end %>
  </div>

src/app/views/profiles/show.html.erb
<%= provide(:active, "container") %>
<%= provide(:banner, 'profiles/banner') %>
<div class='row'>
  <h4><%= @profile.name %></h4>
  <div class="col s12 m12 l6 bio-box "> <!-- style class to be clear:left -->
    <h4 class='black-text'>A little about me...</h4>
    <p class="black-text"><%= @profile.bio %></p>
    <%= show_user_buttons(link_to "Edit Bio", edit_profile_path(@profile)) %>
  </div>
  <div class="col s12 m12 l6 bio-box ">
    <h4>Interest Stuff</h4>
    <p>
      I have <%= @profile.interests.count %> interests
    </p>
    <div class="row">
      <% @profile.interests.each do |interest| %>
        <div class="col s4">
          <%= interest.interest %>
        </div>
      <% end %>
    </div>
    <%= show_user_buttons(link_to "Edit Interests", profile_interests_path(@profile)) %>
  </div>
  <div class="col s12 m12 l6 bio-box superduperleft">
    <% if user_signed_in? && current_user.profile != nil && current_user.profile.id == @profile.user_id %>
      <h4>Mailbox</h4>
      <%= link_to "Inbox", profile_messages_path(@profile) %>
    <% end %>
  </div>
  <div class="col s12 m12 l6 bio-box">
    <% if user_signed_in? && current_user.profile != nil && current_user.id == @profile.user_id %>
      <h4>Who Likes Me?</h4>
      <% @likes.each do |key, value| %>
        <% if !@profile.likes.any? {|p| p.profile_id == value.id} %>
          <div class='row'>
            <div class="col s2">
              <%= image_tag value.avatar_small, :class => 'circle' %>
            </div>
            <div class="col s10 valign-wrapper">
              <p><%= value.name %>
                <%= form_for @profile, url: {action: "update_likes", controller: "profiles", params: {:id => value.id}}, :method => :POST do |f| %>
                  <%= f.submit "Like Back" %>
                <% end %></p>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>
<!--<div class="row">-->
<!--  <div class='col photos'>-->

<!--  </div>-->
<% if user_signed_in? %>
  <% if current_user.profile != nil %>
    <div class="carousel-container">
      <h4><%= @profile.name %>'s Photos</h4>
      <%= link_to "#{@profile.name}'s Photos", profile_photos_path(@profile) %>
      <div class='carousel'>
        <% @profile.photos.each do |photo| %>
          <div class="carousel-item">
              <%= image_tag photo, :class => 'materialboxed' %>
          </div>
        <% end %>
      </div>
    </div>
    <% else %>
      <h4 class='center'><%= link_to "Create your profile to see more good stuff!", new_profile_path %></h4>
    <% end %>
  <% else %>
  <h4 class='center'><%= link_to "Sign in to see more good stuff!", new_user_session_path %></h4>
<% end %>