src/config/routes.rb
Rails.application.routes.draw do

  post 'modal/login' => 'login'
  get 'modal/signup' => 'modal'
  get 'modal/forgot' => 'forgot'


  devise_for :users
  root to: 'profiles#index'

  #Static Pages
  # scope shallow_prefix: "pages" do
    get 'pages/about' => 'pages#about', as: :about
    get 'pages/contact' => 'pages#contact', as: :contact
    get 'pages/testimonies' => 'pages#testimonies', as: :testimonies
  # end


  resources :profiles do
    resources :messages
    resources :payments, only: [:new, :create]
    get '/photos' => 'profiles#photos'#, as: :photos
    get '/hookup' => 'profiles#hookup'
    get '/matches' => 'profiles#matches'
    get '/interests' => 'profiles#interests'
    post '/interests' => 'profiles#update_interests'
  end
  get '/success' => 'payments#success'
  get '/cancel' => 'payments#cancel'
  post '/likes' => 'profiles#update_likes'

  get '/messages' => 'messages#index'

  get "search/index"
    # patch '/profiles/:id'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

src/app/views/partials/_card.html.erb
<div class="col s12 m6 l4">
  <div class="card blue-grey darken-1">
    <div class="card-content white-text">
      <div class="card-profile">
        <span class="card-title"><%= profile.name %></span>
        <%= image_tag profile.avatar_small, :class => 'circle show' %>
      </div>
      <p>
        <% if profile.bio.empty? %>
          I am <%= profile.name %>
        <% else %>
          <%= profile.bio %>
        <% end %>
      </p>
    </div>
    <div class="card-action">
      <%= link_to "#{profile.name.capitalize}'s Profile", profile %>
      <% if user_signed_in? && current_user.profile != nil %>
        <div class="divider"></div>
        <%= link_to "Message #{profile.name.capitalize}", new_profile_message_path(profile, :id => profile.id) %>
      <% end %>
    </div>
  </div>
</div>

src/app/views/partials/_search.html.erb
<% if user_signed_in? %>
  <div class="row">
    <div class='col s12 m6 l6'>
      <%= form_tag search_index_path, method: :get do %>
        <%= text_field_tag :search, "Search for interests" %>
        <%= submit_tag "Search", name: nil %>
      <% end %>
    </div>
  </div>
<% end %>