src/config/routes.rb
Rails.application.routes.draw do

  post 'modal/login' => 'login'
  get 'modal/signup' => 'modal'
  get 'modal/forgot' => 'forgot'


  devise_for :users
  root to: 'profiles#index'

  #Static Pages
  # scope shallow_prefix: "pages" do
    get 'pages/about' => 'pages#about', as: :about
    get 'pages/contact' => 'pages#contact', as: :contact
    get 'pages/testimonies' => 'pages#testimonies', as: :testimonies
  # end


  resources :profiles do
    resources :messages
    resources :payments, only: [:new, :create]
    get '/photos' => 'profiles#photos'#, as: :photos
    get '/hookup' => 'profiles#hookup'
    get '/matches' => 'profiles#matches'
    get '/interests' => 'profiles#interests'
    post '/interests' => 'profiles#update_interests'
  end
  get '/success' => 'payments#success'
  get '/cancel' => 'payments#cancel'
  post '/likes' => 'profiles#update_likes'

  get '/messages' => 'messages#index'

  get "search/index"
    # patch '/profiles/:id'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

src/app/views/layouts/_footer.html.erb
<div class="container">
  <div class="row">
    <div class="col l6 s12">
      <h5 class="white-text">Rails Assessment</h5>
      <p class="grey-text text-lighten-4">Dating application made by Aaron Jones & Glen Johnson</p>
    </div>
    <div class="col l4 offset-l2 s12">
      <h5 class="white-text">Static Links</h5>
      <ul>
        <li><%= link_to "About", about_path, class: "grey-text text-lighten-3" %></li>
        <li><%= link_to "Contact", contact_path, class: "grey-text text-lighten-3" %></li>
        <li><%= link_to "Testimonies", testimonies_path, class: "grey-text text-lighten-3" %></li>
      </ul>
    </div>
  </div>
</div>
<div class="footer-copyright">
  <div class="container">
  © 2019 Copyright Text
  </div>
</div>

src/app/views/layouts/_navbar.html.erb
<nav>
  <div class="nav-wrapper blue">
      <div class="container">
      <%= link_to "Root Path", root_path, :class => "brand-logo" %>
      <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><%= link_to "All Profiles", profiles_path %></li>
          <% if user_signed_in? %>
            <% if current_user.profile == nil %>
              <li><%= link_to "Create my Profile", new_profile_path %></li>
            <% else %>
              <li>Logged in as <%= current_user.profile.name %></li>
              <li><%= link_to "My Profile", profile_path(current_user.profile.id) %></li>
              <li><%= link_to "My Messages", messages_path %></li>
              <li><%= link_to "My Matches", profile_matches_path(current_user.profile) %></li>
              <li><%= link_to "Log Out", destroy_user_session_path, :method => :DELETE %></li>
          <% end %>
        <% else %>
<!--          AJAX call on button press to toggle modal div and load devise login partial-->
          <li><%= button_to "Log In", modal_login_path, {:id => "login-button", :remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window'} %></li>
        <% end %>
      </ul>
      <ul class="sidenav blue" id="mobile-demo">
        <%= link_to "~/ Path", root_path, :class => "brand-logo" %>
        <br>
        <li><%= link_to "All Profiles", profiles_path %></li>
        <% if user_signed_in? %>
          <% if current_user.profile == nil %>
            <li><%= link_to "Create my Profile", new_profile_path %></li>
          <% else %>
            <span>Logged in as <%= current_user.profile.name %></span>
            <li><%= link_to "My Profile", profile_path(current_user.profile.id) %></li>
            <li><%= link_to "My Messages", messages_path(current_user.profile, :id => current_user.profile.id) %></li>
            <li><%= link_to "My Matches", profile_matches_path(current_user.profile) %></li>
            <li><%= link_to "Log Out", destroy_user_session_path, :method => :DELETE %></li>
          <% end %>
        <% else %>
          <li><%= link_to "Log In", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>

  <script>
    document.addEventListener('DOMContentLoaded', function() {
      var elems = document.querySelectorAll('.sidenav');
      var instances = M.Sidenav.init(elems);
    });
  </script>

</nav>

<div id="modal-window" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
    </div>
  </div>
</div>

src/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Assessment</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path ('favicon.ico') %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  </head>

  <body>
    <header>
      <%= render 'layouts/navbar' %>
    </header>
    <main>
      <% if !yield(:banner).empty? %>
        <%= render "#{yield(:banner)}" %>
      <% end %>
      <div class="container">
        <p class="notice"><%= notice %></p>
        <%= yield %>
      </div>
    </main>
    <footer class="page-footer black">
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>